### ISSUE TITLE
no-sync

### ISSUE THREAD

**Issue by eliascodes** [dwyl/goodparts#144]
http://eslint.org/docs/rules/no-sync

There are contexts where sync operations are acceptable and reduce indentation, e.g. in tests or while performing server setup.

```
no-sync: "off"
```

**Comment by jedwards1211** [comment]
@eliascodes personally I just use `async`/`await` instead of sync ops these days

**Comment by eliascodes** [comment]
Hi @jedwards1211, in `goodparts`, we're trying to avoid features that don't have good browser support and require transpilation. You might notice that we set the `ecmaVersion: 5` in our `eslintrc.js` for this reason. Unfortunately this means we can't use `async`/`await`, nice though they are. For another example, see #221

**Comment by jedwards1211** [comment]
Oh, I see.  ES6 will be standard soon enough ;)

**Comment by nelsonic** [comment]
@jedwards1211 ES2015 is _already_ a "Standard" which is _great_! 🎉 
_However_ that does not mean that these new features available _everywhere_. 😞 
It's like proclaiming USB-C is _the_ "standard", it does not mean _all_ devices/peripherals have it. 
And unless you want to use "_dongles_" ("_polyfills_" / "_transpiler_") during the "_transition period_" it's _way_ easier to stick to what _already_ works. (_and then hopefully leapfrog the intermediate step completely like going from PHP straight to Node without doing 3 years of RoR/Apex..._ :wink:)

We are _actively_ investigating `elm-lang` as an _alternative_ to "Transpilation" of ES6/7/8/etc ...
see: https://github.com/dwyl/technology-stack/issues/27

**Comment by jedwards1211** [comment]
Elm is interesting, gaearon cited it as an inspiration for Redux.  But it does require transpilation too, to use in the browser at least.

Personally I find using ES6/7 easier than ES5, even with the added work to set up babel transpilation.  And to deal with that, I just created project skeletons that have everything set up that I use: babel, eslint, flow, mocha, istanbul, etc.

**Comment by nelsonic** [comment]
@jedwards1211 Your project skeletons look like good starting points. 👍 
What your [`devDependency` list](https://github.com/jedwards1211/es2015-library-skeleton/blob/4c6fe662424213175389a1b9a2c29c7cca99b142/package.json#L47-L69) highlights is that you have learned a _lot_ of different things to get to where you are now ... 📚 
BTW: props for your [`crater`](https://github.com/jcoreio/crater) project really well thought out. 😉 

yeah, Elm requires _compilation_ but that's where the similarity to ES6/Babel ends. 😉 
the elm compiler is _smart_ and shows _really **useful**_ "error" messages. 😖  ... ⌛️  `>>` 😂  
The debugger is _fantastic_ and  the language its' self is _microscopic_ by comparison to ES2015. 😍 
I'm not "_sold_" on Elm, _yet_. Because there is a _lot_ to learn and questions to be answered. ❓ 🤔 
But it's come a _long_ way since we checked it out last year so I've decided to `#MakeTime` for it: https://github.com/dwyl/learn-elm/issues `#discuss`

**Comment by jedwards1211** [comment]
Yeah it was definitely a lot to learn and would be horrible for people who are learning to program.  And the amount of things added in ES6 is kind of staggering to me, there are a lot of features I never use.

**Comment by nelsonic** [comment]
@jedwards1211 the sheer _amount_ of learning that is required before people can even _begin_ to contribute to a code project with the React-Redux-ES6 stack is _staggering_ and _most_ people take it for granted. But we _constantly_ try to "_**see the world through the eyes** of a **complete beginner**_". [`#shoshin`](https://github.com/dwyl/start-here#what-do-i-need)

> If I was learning how to code today I would spend a (_few_) week(s) learning JS, build a couple of demo apps and even consider learning a framework or "view" library or two; but then I would learn elm for one of _these_ reasons: https://github.com/dwyl/learn-elm/issues/1
