### ISSUE TITLE
camelcase

### ISSUE THREAD

**Issue by eliascodes** [dwyl/goodparts#216]
http://eslint.org/docs/rules/camelcase

```
camelcase: "error"
```

Prefer consistent naming convention, camel case is more idiomatic of javascript.

**Comment by SimonLab** [comment]
I prefer using camelCase but this one is tricky, a lot of people prefer using other styles for naming variables and functions. I agree we need consistency but I'm not sure if camelcase is the right one to choose.

**Comment by nelsonic** [comment]
@eliascodes I _agree_ that `camelCase` is "_idiomatic_" in JS for _method_ names. 👍 
I prefer `snake_case` to `camelCase` but I don't have a "_valid_" reason other than letting the words "breathe"... 
(AFAIK) There isn't anything in "The Good Parts" that _dictates_ variable naming convention.
And we already use `ALL_CAPS_SEPARATED_BY_UNDERSCORES` for environment variables 
see: https://github.com/dwyl/learn-environment-variables#environment-variable-naming-convention
Which I think makes things _really_ clear.

What I'm tempted to say is: 
+ method/function names should be `camelCase`
+ property/variable names should be `snake_case`

I _think_ this would be _reasonably **beginner friendly**_ ... thoughts?
This is the subject of many "_flame wars_", e.g: https://news.ycombinator.com/item?id=6777750

possibly related to: https://github.com/dwyl/abase/issues/24 and https://github.com/dwyl/abase/issues/26

**Comment by cristinecula** [comment]
Will you be mostly using hapi as the framework?
If that's the case you should probably adhere to the hapi style guide:
http://hapijs.com/styleguide#variable-declarations

> Use camelCase, never underscores

**Comment by eliascodes** [comment]
@nelsonic having a quick look at the rule specification, I can't see a way to implement that split between methods/functions and properties/variables. This would require us to write a new rule. I don't have a particularly strong opinion, and can see how your suggestion would make it clear what names hold values and which hold functions.

@cristinecula We do use hapi, although I don't think we feel bound by their style-guide. For example, hapi's styleguide recommends using `const` and `let` over `var`, whereas we do the opposite for various reasons (see #13 and #10), as well as it being recommended in `The Good Parts`

**Comment by nelsonic** [comment]
@cristinecula that's a _really good question_! (_and something that requires clarification_)
Yes, we are using `hapi` because we think it's the most _well-tested_ and simplest HTTP framework in Node.js-land. see: https://github.com/dwyl/learn-hapi#why-hapi-instead-of-xyz-framework

_However_ using `hapi` does _not_ mean we _have_ to follow `hapi` style guide. 
(_to be clear we actually like **most** of the "rules" in the Hapi style-guide and we are _stoked_ that the Hapi team have a good standard, but they are very **server-focussed** and **not generally applicable** to **all JS code**_...)

for example: Variable Declarations http://hapijs.com/styleguide#variable-declarations
![hapi-variable-declarations](https://cloud.githubusercontent.com/assets/194400/18780716/d2e2d094-8176-11e6-8c45-941a59af2610.png)

Sure, we can use `const` and `let` on a node.js (hapi) server, but the objective of this repo is to give people a lint config they can use to write code that "***Works Everywhere<sup>TM</sup>***" 
(_i.e. we don't plan on using `goodparts` **only** for `hapi` projects..._).

see: 
+ `let`: https://github.com/dwyl/goodparts/issues/10
+ `const`: https://github.com/dwyl/goodparts/issues/13

**Comment by nelsonic** [comment]
@eliascodes did you see http://eslint.org/docs/rules/camelcase#never ?
again, I would make the _case_ for encourage this because it makes the distinction between methods and properties _immediately obvious_. 
More this:
![image](https://cloud.githubusercontent.com/assets/194400/18781689/c9f78d36-817a-11e6-9544-e1aa1dbe8ca5.png)

Less this:
![image](https://cloud.githubusercontent.com/assets/194400/18781701/d584549a-817a-11e6-8905-9d7d8b37e0ab.png)

For _now_ I would _suggest_ that we keep this rule set to:
```
camelcase: ["error", {properties: "never"}]
```
To me this makes our code more _beginner-friendly_ ... but as always I'm _all ears_ for a different perspective.

**Comment by eliascodes** [comment]
@nelsonic doesn't that still force you to write variables in camel case? i.e. it would make
```javascript
var myCamelCaseVar = 1;
```
valid but
```javascript
var my_snake_case_var = 1;
```
invalid. This is still one step closer to what you want, but not exactly it. But happy to change to your suggestion if you're happy with this.

**Comment by nelsonic** [comment]
busy updating _existing_ code to use `goodparts`
_really_ not a fan of being _forced_ to use `camelCase` ... 😞

**Comment by eliascodes** [comment]
@nelsonic with stylistic rules, I don't have particularly strong feelings. Happy to change to `"off"` if you'd like (and if no one else objects).

**Comment by nelsonic** [comment]
@eliascodes if no-one else objects, I would be grateful if this was turned off ... not "urgent" tho.
(_I've changed all the `snake_case` in the code I'm busy with to `camelCase` in the short-term ..._)

**Comment by SimonLab** [comment]
ok let's give a try to snake case, @nelsonic do you use snake case for everything (function name, variables, properties)?

**Comment by nelsonic** [comment]
@SimonLab good question. I want to make the _case_ `snake_case` for variables and Object properties  ... but in the _past_, yes I have used `snake_case` for functions too ... but I would _never_ force that on anyone else. and I would _rather_ have something _consistent_ that I _personally_ didn't like than a personal preference that opened the floodgates to inconsistency... :thinking:

**Comment by iteles** [comment]
A note on this here: https://github.com/dwyl/style-guide#variable-naming

**Comment by nelsonic** [comment]
These guys did the _**Science**_: 
[ICPC2010-camelCase-vs-underscore.pdf](https://github.com/dwyl/goodparts/files/515115/ICPC2010-CamelCaseUnderScoreClouds.pdf)

> have you found any other _empirical_ studies that support `camelCase` as being "faster to read"...? (_not the dogmatic "that's how JS language features are implemented so we should follow the leader..."_)
