### ISSUE TITLE
no-magic-numbers

### ISSUE THREAD

**Issue by SimonLab** [dwyl/goodparts#92]
http://eslint.org/docs/rules/no-magic-numbers

```
no-magic-numbers: 0
```

I'm not sure creating more variables or constant will make the code more readable

**Comment by nelsonic** [comment]
In a simple date-based calculation, it (_usually_) quite obvious (_to relatively experienced developers_) what the numbers mean:
```js
var tomorrow = new Date(new Date().getTime() + 24 * 60 * 60 * 1000);
console.log(tomorrow);
```
So it can _feel_ a bit "_tedious_" to create a variable for each number: https://repl.it/Dguu/1
```
var milliseconds = 1000;
var seconds = 60;
var minutes = 60;
var hours = 24;
var one_day = hours * minutes * seconds * milliseconds;
var today = Date.now();
var tomorrow = new Date(today + one_day).toISOString();
console.log(tomorrow);
```

But in a slightly more "_real world_" example, can we think of a _reason_ to have numbers in our code without declaring a variable or constant ? e.g:

```js
var income_after_tax = income - income * 0.2; // 20% income tax
```

What happens when the rate of tax changes? do we have to _find-and-replace_?
isn't it easier:
```js
var income_tax_rate = 0.20; // 20% income tax
var income_after_tax = income - income * income_tax_rate; 
```
